CREATE TABLE IF NOT EXISTS `template` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `page` VARCHAR(50) NULL DEFAULT NULL,
  `group` VARCHAR(50) NULL DEFAULT NULL,
  `tpl` LONGTEXT NULL,
  `js` LONGTEXT NULL,
  `path` ENUM('CORE','WWW') NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
;
