CREATE TABLE `routes` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`route` VARCHAR(500) NULL DEFAULT NULL,
	`request_method` VARCHAR(25) NULL DEFAULT NULL,
	`controller` VARCHAR(255) NULL DEFAULT NULL,
	`method` VARCHAR(255) NOT NULL,
	`access` INT NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
;
