name: Generate next version

on:
  push:
    branches:
    - master
    - hotfix/*

jobs:
  generate:
    name: auto set verion
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previous
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previous.outputs.tag }}

      - name: Create
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.semvers.outputs.patch }}
          token: ${{ secrets.GITHUB_TOKEN }}
