name: Generate next version

on:
  push:
    branches:
    - master
    - develop
    paths-ignore:
    - '**.md'
    - '**.yml'

jobs:
  generate:
    name: auto-update
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previous
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: 'Get next version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previous.outputs.tag }}

      - name: minor
        if: ${{ github.ref == 'refs/heads/develop' }}
        env:
          ver: ${{ steps.semvers.outputs.minor }}

        uses: negz/create-tag@v1

        with:
          version: ${{ steps.semvers.outputs.minor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: patch
        if: ${{ github.ref != 'refs/heads/develop' }}
        env:
          ver: ${{ steps.semvers.outputs.patch }}
          
        uses: negz/create-tag@v1
        
        with:
          version: ${{ steps.semvers.outputs.patch }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: release patch
        if: ${{ steps.patch.ver == true }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.semvers.outputs.patch }}
          title: ${{ steps.semvers.outputs.patch }}
          prerelease: false
          files: |
            *

      - name: release minor
        if: ${{ steps.minor.ver == true }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.semvers.outputs.minor }}
          title: ${{ steps.semvers.outputs.minor }}
          prerelease: false
          files: |
            *
